version: '3.8'
services:
  # Service web : conteneur pour le site web
  web:
    build:
      context: site
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/
      - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./server/apache2.conf:/etc/apache2/apache2.conf
      - ./server/php/php.ini:/usr/local/etc/php/php.ini

  # Service DB : conteneur pour une base de données MySQL
  database:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./database:/var/lib/mysql # Stockage des données de la base de données
      - ./script/script.sql:/script.sql # Script SQL à exécuter au démarrage du conteneur

  # Service phpMyAdmin : interface d'administration de MySQL
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    depends_on:
      - database
  
volumes:
  database: